# Generated by Django 4.1.5 on 2023-05-05 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0003_product_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='article',
        ),
    ]
